defaults:
  - _self_
  - report: overtime
  - stages: ${report}
  - figs: ${report}
log_level: INFO
n_bootstrap: 1_000
plot_format: png

weighting:
  - weight_col: equal_task_weight
    graph_snippet: Equally weighted tasks
  - weight_col: invsqrt_task_weight
    graph_snippet: Tasks diversity-weighted (1/sqrt(# tasks in family))
  - weight_col: null
    graph_snippet: "None"

stages:
  filter_aird_runs:
    task_families:
      - ai_rd_fix_embedding
      - ai_rd_nanogpt_chat_rl
      - ai_rd_optimize_llm_foundry
      - ai_rd_restricted_mlm
      - ai_rd_rust_codecontests_inference
      - ai_rd_small_scaling_law
      - ai_rd_triton_cumsum

rebench_best_of_k_parameters:
  time_limits: [36000]
  max_time_limit_in_seconds: 36000

plots:
  suptitle_fontsize: 18
  xlabelpad: 10
  ylabelpad: 10
  ax_label_fontsize: 14
  title_fontsize: 16

  task_distribution_styling:
    hist:
      edgecolor: "#a6a6a6"
      color: "#d4d4d4"
      alpha: 1
      linewidth: 1
      zorder: 50
    grid: &grid_styling
      which: "major"
      linestyle: "-"
      alpha: 0.2
      color: "grey"

  scatter_styling:
    error_bar:
      color: "grey"
      fmt: "none"
      capsize: 2
      alpha: 1
      zorder: 9
      linewidth: 1.5
      capthick: 1.5
    grid: *grid_styling
    scatter:
      s: 150
      edgecolor: "black"
      linewidth: 0.5
      zorder: 10

  agent_styling:
    "Claude 3.5 Sonnet (New)":
      lab_color: &anthropic_color "#e26e2f"
      marker: "s"
      unique_color: "#8B4DC9"
    "Claude 3.5 Sonnet (Old)":
      lab_color: *anthropic_color
      marker: "^"
      unique_color: "#9B6BE0"
    "Claude 3 Opus":
      lab_color: *anthropic_color
      marker: "o"
      unique_color: "#B594E8"
    "o1":
      lab_color: &openai_color "#3e805f"
      marker: "P"
      unique_color: "#228B22"
    "o1-preview":
      lab_color: *openai_color
      marker: "X"
      unique_color: "#3CB371"
    "GPT-4o":
      lab_color: *openai_color
      marker: "d"
      unique_color: "#2B8FB0"
    "GPT-4 Turbo":
      lab_color: *openai_color
      marker: "v"
      unique_color: "#4A9CBD"
    "GPT-4 1106":
      lab_color: *openai_color
      marker: "D"
      unique_color: "#87CEEB"
    "GPT-4 0314":
      lab_color: *openai_color
      marker: "s"
      unique_color: "#87CEEB"
    "gpt-3.5-turbo-instruct":
      lab_color: *openai_color
      marker: "^"
      unique_color: "#CCE6FF"
    "davinci-002 (GPT-3)":
      lab_color: *openai_color
      marker: "o"
      unique_color: "#B3E0FF"
    "GPT-2":
      lab_color: *openai_color
      marker: "*"
      unique_color: "#CCE6FF"
    "human":
      lab_color: "grey"
      marker: "o"
      unique_color: "#858585"
    "default":
      lab_color: "black"
      marker: "o"
      unique_color: "black"
  performance_over_time_trendline_styling:
    "linear":
      annotation:
        color: &linear_trend_color "red"
        fontsize: &annotation_fontsize 10
      line:
        color: *linear_trend_color
        alpha: &trendline_alpha 0.5
        linewidth: &trendline_linewidth 2
    "exponential":
      annotation:
        color: &exponential_trend_color "blue"
        fontsize: *annotation_fontsize
      line:
        color: *exponential_trend_color
        alpha: *trendline_alpha
        linewidth: *trendline_linewidth
    "hyperbolic":
      annotation:
        color: &hyperbolic_trend_color "green"
        fontsize: *annotation_fontsize
      line:
        color: *hyperbolic_trend_color
        alpha: *trendline_alpha
        linewidth: *trendline_linewidth
    "default":
      annotation:
        color: "black"
        fontsize: *annotation_fontsize
      line:
        color: "black"
        alpha: *trendline_alpha
        linewidth: *trendline_linewidth

  legend_order:
    - Claude 3.5 Sonnet (New)
    - Claude 3.5 Sonnet (Old)
    - Claude 3 Opus
    - o1
    - o1-preview
    - GPT-4o
    - GPT-4 Turbo
    - GPT-4 1106
    - GPT-4 0314
    - gpt-3.5-turbo-instruct
    - davinci-002 (GPT-3)
    - GPT-2
    - Human 8-hour score
