stages:
  generate_task_summaries:
    cmd:
      - &git_checkout_mp4_tasks >-
        [ -d /tmp/tasks ]
        || git clone ${tasks_repo.url} /tmp/tasks
        && cd /tmp/tasks
        && git fetch
        && git checkout ${tasks_repo.rev}
      - >-
        python -m src.task_summaries
        --task-repo-dir=/tmp/tasks
        --few-shot-examples=data/summary_examples.txt
        --model=claude-3-7-sonnet-20250219
        --output-path=data/task_summaries.yaml
    deps:
      - src/task_summaries.py
      - data/summary_examples.txt
      - params.yaml
    outs:
      - data/task_summaries.yaml:
          persist: true
    frozen: true
  generate_latex_tables:
    cmd:
      - *git_checkout_mp4_tasks
      - >-
        python -m src.generate_latex_tables
        --task-repo-dir=/tmp/tasks
        --difficulty-file=../../data/external/task_difficulty.yaml
        --blueprint-file=../../data/external/blueprints/benchmark.yaml
        --labels-file=../../data/external/family_labels.yaml
        --summaries-file=data/task_summaries.yaml
        --output-dir=tables
    deps:
      - src/generate_latex_tables.py
      - ../../data/external/task_difficulty.yaml
      - ../../data/external/blueprints/benchmark.yaml
      - ../../data/external/family_labels.yaml
      - data/task_summaries.yaml
      - params.yaml
    metrics:
      - tables/family_summary_table.tex
      - tables/contamination_distribution_table.tex
      - tables/expertise_distribution_table.tex
      - tables/category_distribution_table.tex
      - tables/qualitative_properties_table.tex
