params:
  - fig_params/figs.yaml

vars:
  - fig_params/figs.yaml

stages:
  generate_agent_summary:
    cmd: >-
      python -m horizon.agent_summary
      --input-file data/raw/runs.jsonl
      --output-file-prefix metrics/agent_summary.csv
      --output-metrics-file metrics/scores_by_agent_and_task.yaml
    deps:
      - ../../src/horizon/agent_summary.py
      - data/raw/runs.jsonl
    params:
      - agent_summary.agents
    outs:
      - metrics/agent_summary.csv:
          cache: false
      - metrics/agent_summary_nonzero.csv
      - metrics/agent_summary_averages.csv
    desc: Get number of runs (metrics/agent_summary.csv), number of runs with nonzero score (metrics/agent_summary_nonzero.csv), and average score for each agent (metrics/agent_summary_averages.csv).

  # Wrangle

  # n-bootstrap should be 10000 in the final version
  wrangle_bootstrap_logistic:
    foreach: &foreach_logistic
      headline: ${figs.wrangle_logistic.headline}
      ga_rebench: ${figs.wrangle_logistic.ga_rebench}
    do:
      cmd: >-
        python -m horizon.wrangle.bootstrap
        --fig-name ${key}
        --runs-file ${item.runs_file}
        --output-bootstrap-horizons-file data/wrangled/bootstrap/${key}.csv
        --n-bootstrap ${n_bootstrap}
      deps:
        - ../../src/horizon/wrangle/bootstrap.py
        - ../../src/horizon/utils/logistic.py
        - ${item.runs_file}
      params:
        - fig_params/figs.yaml:
            - figs.wrangle_logistic.${key}
        - n_bootstrap
      outs:
        - data/wrangled/bootstrap/${key}.csv
      desc: Compute bootstrapped logistic regression results

  wrangle_logistic_regression:
    foreach: *foreach_logistic
    do:
      cmd: >-
        python -m horizon.wrangle.logistic
        --fig-name ${key}
        --runs-file ${item.runs_file}
        --output-logistic-fits-file data/wrangled/logistic_fits/${key}.csv
        --release-dates ../../data/external/release_dates.yaml
        --bootstrap-file data/wrangled/bootstrap/${key}.csv
        --output-metrics-file metrics/logistic_fits/${key}.yaml
      deps:
        - ${item.runs_file}
        - ../../data/external/release_dates.yaml
        - data/wrangled/bootstrap/${key}.csv
        - ../../src/horizon/wrangle/logistic.py
        - ../../src/horizon/utils/logistic.py
      params:
        - fig_params/figs.yaml:
            - figs.wrangle_logistic.${key}
      outs:
        - data/wrangled/logistic_fits/${key}.csv
      metrics:
        - metrics/logistic_fits/${key}.yaml:
            cache: false
      desc: Fit logistic curves for each agent, load bootstrap results from bootstrap stage, and add binned weighted success rate data.

  # Plot

  plot_individual_histograms:
    foreach: ${figs.plot_individual_histograms}
    do:
      cmd: >-
        python -m horizon.plot.individual_histograms
        --all-runs-file data/raw/runs.jsonl
        --output-file plots/individual_histograms/${key}/histograms.${plot_format}
        --plot-format ${plot_format}
        --log-level ${log_level}
        --script-parameter-group ${key}
        --params-file "params.yaml"
      deps:
        - ${item.logistic_file}
        - data/raw/runs.jsonl
        - matplotlibrc
        - ../../src/horizon/plot/individual_histograms.py
        - ../../src/horizon/utils/plots.py
      params:
        - log_level
        - plot_format
        - plots
        - fig_params/figs.yaml:
            - figs.plot_individual_histograms.${key}
      outs:
        - plots/individual_histograms/${key}/histograms.${plot_format}:
            persist: true

      desc: Logistic success curve + bars for each agent.

  plot_logistic_regression:
    foreach:
      double_line_all_data_retrodict_excluding_swaa: ${figs.plot_logistic_regression.double_line_all_data_retrodict_excluding_swaa}
      double_line_2024_trendline: ${figs.plot_logistic_regression.double_line_2024_trendline}
    do:
      cmd: >-
        python -m horizon.plot.logistic
        --input-file data/wrangled/logistic_fits/${item.logistic_file}.csv
        --runs-file ${item.runs_file}
        --release-dates ../../data/external/release_dates.yaml
        --output-file plots/logistic/${key}.${plot_format}
        --log-level ${log_level}
        --script-parameter-group ${key}
      deps:
        - ${item.runs_file}
        - data/wrangled/logistic_fits/${item.logistic_file}.csv
        - data/wrangled/logistic_fits/ga_rebench.csv  # Required for double_line trendlines
        - matplotlibrc
        - ../../data/external/release_dates.yaml
        - ../../src/horizon/plot/logistic.py
        - ../../src/horizon/utils/plots.py
      params:
        - log_level
        - plot_format
        - plots
        - fig_params/figs.yaml:
            - figs.plot_logistic_regression.${key}
      outs:
        - plots/logistic/${key}.${plot_format}:
            persist: true
      desc: Plot showing horizon growth over time.

  plot_bootstrap_ci:
    matrix:
      fig_name: [headline, twitter_headline]
      y_scale: [log, linear]
    cmd: >-
      python -m horizon.plot.bootstrap_ci
      --fig-name ${item.fig_name}
      --input-file data/wrangled/bootstrap/headline.csv
      --agent-summaries-file data/wrangled/logistic_fits/headline.csv
      --release-dates ../../data/external/release_dates.yaml
      --output-file plots/bootstrap/${item.fig_name}-${item.y_scale}.${plot_format}
      --log-level ${log_level}
      --y-scale ${item.y_scale}
    deps:
      - ../../src/horizon/plot/bootstrap_ci.py
      - ../../src/horizon/plot/logistic.py # dependency on plot_trendline
      - data/wrangled/bootstrap/headline.csv
      - data/wrangled/logistic_fits/headline.csv
      - ../../data/external/release_dates.yaml
      - matplotlibrc
    params:
      - log_level
      - plot_format
      - plots
      - fig_params/figs.yaml:
          - figs.plot_logistic_regression.${item.fig_name}
    plots:
      - plots/bootstrap/${item.fig_name}-${item.y_scale}.${plot_format}
    desc: Generate plot of bootstrap confidence intervals

  compute_trendline_ci:
    foreach:
      headline_from_2019:
        after_date: "2019-01-01"
        before_date: "2030-01-01"
        data_file: headline
      headline_from_2023:
        after_date: "2023-03-13"
        before_date: "2030-01-01"
        data_file: headline
      headline_from_2024:
        after_date: "2024-01-01"
        before_date: "2030-01-01"
        data_file: headline
      ga_rebench_from_2023:
        after_date: "2023-03-13"
        before_date: "2030-01-01"
        data_file: ga_rebench
      ga_rebench_from_2024:
        after_date: "2024-01-01"
        before_date: "2030-01-01"
        data_file: ga_rebench
      original_overtime: # reported in the original paper
        after_date: "2019-01-01"
        before_date: "2025-02-25"
        data_file: headline
      original_overtime_from_2023: # reported in the original paper
        after_date: "2023-01-01"
        before_date: "2025-02-25"
        data_file: headline
      # was reported in the original paper as 104, but only in the SWE-Bench Verified section,
      # which makes me suspect this may be older data...
      original_overtime_from_2024:
        after_date: "2024-01-01"
        before_date: "2025-02-25"
        data_file: headline
      original_overtime_only_2024:
        after_date: "2024-01-01"
        before_date: "2024-12-31"
        data_file: headline
      post_gpt_4_inclusive:
        after_date: "2023-03-13"
        before_date: "2030-01-01"
        data_file: headline
    do:
      cmd: >-
        python -m horizon.compute_trendline_ci
        --input-file data/wrangled/bootstrap/${item.data_file}.csv
        --agent-summaries-file data/wrangled/logistic_fits/${item.data_file}.csv
        --release-dates ../../data/external/release_dates.yaml
        --output-metrics-file metrics/trendline_ci/${key}.yaml
        --log-level ${log_level}
        --after-date ${item.after_date}
        --before-date ${item.before_date}
      deps:
        - ../../src/horizon/compute_trendline_ci.py
        - ../../src/horizon/plot/bootstrap_ci.py
        - ../../src/horizon/plot/logistic.py
        - data/wrangled/bootstrap/${item.data_file}.csv
        - data/wrangled/logistic_fits/${item.data_file}.csv
        - ../../data/external/release_dates.yaml
      params:
        - log_level
      metrics:
        - metrics/trendline_ci/${key}.yaml:
            cache: false
      desc: Compute trendline confidence interval metrics from bootstrap samples using SOTA models

  generate_benchmark_results:
    cmd: >-
      python -m horizon.generate_benchmark_results
      --agent-summaries-file data/wrangled/logistic_fits/headline.csv
      --runs-file data/raw/runs.jsonl
      --release-dates-file ../../data/external/release_dates.yaml
      --bootstrap-results-file data/wrangled/bootstrap/headline.csv
      --output-metrics-file metrics/benchmark_results.yaml
      --benchmark-name ${benchmark.name}
      --benchmark-long-tasks-version ${benchmark.long_tasks_version}
      --benchmark-swaa-version ${benchmark.swaa_version}
    deps:
      - ../../src/horizon/generate_benchmark_results.py
      - ../../src/horizon/compute_trendline_ci.py
      - ../../src/horizon/plot/bootstrap_ci.py
      - data/wrangled/bootstrap/headline.csv
      - data/wrangled/logistic_fits/headline.csv
      - data/raw/runs.jsonl
      - ../../data/external/release_dates.yaml
    params:
      - benchmark.name
      - benchmark.long_tasks_version
      - benchmark.swaa_version
    metrics:
      - metrics/benchmark_results.yaml:
          cache: false

  compare_trend:
    cmd: >-
      python -m horizon.compare_trend
      --bootstrap-results-file data/wrangled/bootstrap/headline.csv
      --release-dates-file ../../data/external/release_dates.yaml
      --output-metrics-file metrics/compare_trend_headline_latest_agent_test.yaml
      --output-max-metrics-file metrics/compare_max_headline_latest_agent_test.yaml
    deps:
      - ../../src/horizon/compare_trend.py
      - data/wrangled/bootstrap/headline.csv
      - ../../data/external/release_dates.yaml
    params:
      - fig_params/figs.yaml:
          - figs.compare_trend
    metrics:
      - metrics/compare_trend_headline_latest_agent_test.yaml
      - metrics/compare_max_headline_latest_agent_test.yaml

  compare_doubling_times_vs_th_1_0:
    cmd: >-
      python -m horizon.plot.compare_doubling_times
      --bootstrap-file-1 data/wrangled/bootstrap/headline.csv
      --agent-summaries-file-1 data/wrangled/logistic_fits/headline.csv
      --label-1 "TH 1.1"
      --bootstrap-file-2 ../time-horizon-1-0/data/wrangled/bootstrap/headline.csv
      --agent-summaries-file-2 ../time-horizon-1-0/data/wrangled/logistic_fits/headline.csv
      --label-2 "TH 1.0"
      --release-dates ../../data/external/release_dates.yaml
      --after-date "2023-01-01"
      --output-plot-file plots/compare_doubling_times_vs_th_1_0.${plot_format}
      --plot-format ${plot_format}
      --log-level ${log_level}
    deps:
      - ../../src/horizon/plot/compare_doubling_times.py
      - ../../src/horizon/plot/bootstrap_ci.py
      - ../../src/horizon/plot/logistic.py
      - ../../src/horizon/compute_trendline_ci.py
      - data/wrangled/bootstrap/headline.csv
      - data/wrangled/logistic_fits/headline.csv
      - ../time-horizon-1-0/data/wrangled/bootstrap/headline.csv
      - ../time-horizon-1-0/data/wrangled/logistic_fits/headline.csv
      - ../../data/external/release_dates.yaml
    params:
      - log_level
      - plot_format
      - comparison_color_1
      - comparison_color_2
    plots:
      - plots/compare_doubling_times_vs_th_1_0.${plot_format}:
          persist: true
    desc: Compare bootstrapped doubling times between time-horizon-1-1 and time-horizon-1-0 model reports for 2023+ SOTA models
