name: Side-by-side plots

on:
  pull_request:
    branches: [main]

jobs:
  compare-plots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for comparison

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry

      - uses: iterative/setup-cml@v1

      - name: poetry install
        run: |-
          poetry install
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Compare plots across repositories
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking plots"

          # Populate dvc_plots dir
          dvc plots diff main ${{ github.head_ref || github.ref_name }}
          if [ -d "dvc_plots" ]; then
            ls -R dvc_plots
          fi

          # compare with current branch
          echo "Comparing with ${{ github.head_ref || github.ref_name }}"
          poetry run python .github/scripts/compare_plots.py --old-branch main --new-branch ${{ github.head_ref || github.ref_name }}
          if [ -d "changed_plots" ]; then
            ls -R changed_plots
          fi

          cml comment update changed_plots/summary.md
